[package]
name = "dag-pb"
version = "0.0.1"
description = "A Motoko library for encoding and decoding DAG-PB (DAG-Protobuf) data structures used by IPFS."
repository = "https://github.com/edjcase/motoko_dag_pb"
keywords = [ "dag", "protobuf", "ipfs", "unixfs", "encode", "decode" ]
license = "MIT"

[dependencies]
base = "0.15.0"
cid = "0.2.0"
protobuf = "0.0.3"
core = "0.6.0"

[dev-dependencies]
test = "2.1.1"

[toolchain]
moc = "0.14.14"
